---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: openeo-geotrellis
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "vito-docker.artifactory.vgt.vito.be/openeo-geotrellis"
  imagePullPolicy: Always
  mainApplicationFile: local:///usr/local/lib/python3.7/dist-packages/openeogeotrellis/deploy/kubernetes.py
  sparkConf:
    "spark.executorEnv.DRIVER_IMPLEMENTATION_PACKAGE": "openeogeotrellis"
    "spark.extraListeners": "org.openeo.sparklisteners.CancelRunawayJobListener"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    envVars:
      KUBE_OPENEO_API_PORT: "50001"
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
      name: openeo-geotrellis-driver
    serviceAccount: sparkoperator-1593094592-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5
  deps:
    jars:
      - 'local:///opt/geotrellis-extensions-1.4.0-SNAPSHOT.jar'
      - 'local:///opt/geotrellis-backend-assembly-0.4.5-openeo.jar'
    files:
      - 'local:///opt/layercatalog.json'
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/jmx_prometheus_javaagent-0.13.0.jar"
      port: 8090
